# Site settings
title:            Polar Game Engine
description:      Polar Game Engine is a modern, safe game engine written in Haskell.
baseurl:          ""
url:              "https://polarengine.org"
github_username:  polar-engine
freenode_channel: polar

# Build settings
markdown: kramdown
